apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-devbook.fullname" . }}-config
  labels:
    {{- include "api-devbook.labels" . | nindent 4 }}
data:
  DB_USER: "devbook"
  DB_PASS: "devbook"
  DB_NAME: "devbook"
  DB_HOST: "mysql.default.svc.cluster.local"
  DB_PORT: "3306"
  API_PORT: "5000"
  SECRET_KEY: "IHyAVIwovJzMx8KjX7jY2cNoZU+ZFItKmK3jhl1wykMRtqCFVGWGQuppdVHVcRNRCsh07qOTO0OwW5164CdrBA=="