apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-devbook.fullname" . }}
  labels:
{{ include "api-devbook.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: {{ .Values.service.port }}
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "api-devbook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
