{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "api-devbook.serviceAccountName" . }}
  labels:
{{ include "api-devbook.labels" . | indent 4 }}
{{- end -}}
